import type { FormData } from "@/lib/frontend/types/form";

const dummyFormData: FormData = {
  profile: {
    fullName: "",
    title: "",
    bio: "",
    avatar: "",
    bannerImage: "",
    about: "",
    headers: [],
    links: [],
    embeds: [],
    testimonials: [],
    faqs: [],
    services: [],
    featured: [],
    tags: [],
    fullAddress: "",
    latitude: "",
    longitude: "",
    email: "",
    phone: "",
    website: "",
    whatsapp: "",
    showContactForm: false,
    resumeUrl: "",
    socials: {
      youtube: "",
      instagram: "",
      calendly: "",
      facebook: "",
      LinkedIn: "",
    },
  },
  design: {
    theme: "brand",
    emojiLink: "",
    brandingOff: false,
    layoutType: "bio",
  },
  settings: {
    nsfwWarning: false,
    preferredLink: "primary",
    customDomain: "",
    gaId: "",
    subdomain: "",
    seo: {
      metaTitle: "",
      metaDescription: "",
      metaKeywords: [],
      canonicalUrl: "",
      ogTitle: "",
      ogDescription: "",
      ogImage: "",
      twitterTitle: "",
      twitterDescription: "",
      twitterImage: "",
      noIndex: false,
      noFollow: false,
    },
  },
  posts: { posts: [] },
  subscriberSettings: {
    SubscriberList: { data: [], total: 0, active: 0, unsubscribed: 0 },
    subscriberSettings: {
      hideSubscribeButton: false,
      subject: "",
      thankYouMessage: "",
    },
  },
  stats: {
    linkClicks: [],
    trafficSources: [],
    contactSubmissions: [],
    topLinks: [],
  },
};

export default dummyFormData;
